#!/bin/sh
### BEGIN INIT INFO
# Provides:
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO
name=`basename $0`
dir="@DIR@"
user="@USER@"
export JAVA_HOME=`/bin/readlink -f $(which java) | sed -e 's:/bin/java$::'`

case "$1" in
    start)
        su $user -c $dir/pingfederate-run.sh
    ;;
    stop)
        su $user -c $dir/pingfederate-shutdown.sh
    ;;
    restart)
    $0 stop
    $0 start
    ;;
    *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac
exit 0

